### ISSUE TITLE
Compile error in Swift 3.0.2

### ISSUE THREAD

**Issue by gianfilippocisternino** [ra1028/FloatingActionSheetController#5]
I got this compile error:
overriding var must be as accessible as its enclosing type

The problem is related to the property **isHighlighted** of the class **ActionButton**: it can't be less visible than the superclass.

Please fix it,
Thank you

**Comment by sudhir-oab** [comment]
Same error comes for me as well for below line in "**ActionButton**" class.
`override private var isHighlighted: Bool {`
It says 

> **overriding var must be as accessible as its enclosing type**

**Comment by gbettinazzi** [comment]
Same error here "overriding var must be as accessible as its enclosing type" @ra1028 is there a fix coming for this? Thank u

**Comment by staticdreams** [comment]
The fix is trivial. I fixed this and submitted a PR
Check out my fork if this does not get through
